import { printToFileAsync } from 'expo-print';
import { shareAsync } from 'expo-sharing';
import { Semester, User } from '../types';
import { calculateSemesterGPA, calculateCGPA } from '../utils/calculations';
import { Platform } from 'react-native';

const generateHTML = (user: User | null, semesters: Semester[]) => {
    const sortedSemesters = [...semesters].sort((a, b) => b.timestamp - a.timestamp);
    const cgpa = calculateCGPA(semesters);

    const semesterRows = sortedSemesters.map(sem => {
        let coursesHtml = '';

        // Check if it's a Quick Add semester
        const isQuickAdd = sem.courses.length === 0 && sem.gpa !== undefined;

        if (isQuickAdd) {
            coursesHtml = `
        <tr class="course-row quick-add">
          <td colspan="3"><i>Summary Record (Quick Add)</i></td>
          <td>${sem.totalUnits}</td>
          <td>-</td>
          <td>${sem.gpa?.toFixed(2)}</td>
        </tr>
      `;
        } else {
            coursesHtml = sem.courses.map(course => {
                // Calculate points (Units * Grade Points) - simplified approximation for display
                // In reality we'd need the grade points mapping.
                // But for transcript, usually just Grade is shown.
                return `
        <tr class="course-row">
          <td>${course.code}</td>
          <td>${course.name}</td>
          <td>${course.unitHours}</td>
          <td>${course.grade || '-'}</td>
          <td>${course.finalScore || '-'}</td>
        </tr>
      `;
            }).join('');
        }

        const semGPA = isQuickAdd ? sem.gpa : calculateSemesterGPA(sem.courses);

        return `
      <div class="semester-block">
        <div class="semester-header">
          <h3>${sem.name}</h3>
          <span class="semester-gpa">GPA: ${semGPA?.toFixed(2) || '0.00'}</span>
        </div>
        <table>
          <thead>
            <tr>
              <th>Code</th>
              <th>Title</th>
              <th>Units</th>
              <th>Grade</th>
              <th>Score</th>
            </tr>
          </thead>
          <tbody>
            ${coursesHtml}
          </tbody>
        </table>
      </div>
    `;
    }).join('');

    return `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica', sans-serif; color: #333; padding: 20px; }
          .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #000; padding-bottom: 20px; }
          .logo { font-size: 24px; font-weight: bold; color: #1a237e; margin-bottom: 5px; }
          .subhead { font-size: 14px; color: #666; }
          .user-info { margin-bottom: 30px; }
          .user-info p { margin: 5px 0; font-size: 14px; }
          .semester-block { margin-bottom: 25px; page-break-inside: avoid; }
          .semester-header { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #ddd; padding-bottom: 5px; margin-bottom: 10px; }
          .semester-header h3 { margin: 0; font-size: 16px; color: #1565c0; }
          .semester-gpa { font-weight: bold; font-size: 14px; }
          table { width: 100%; border-collapse: collapse; font-size: 12px; }
          th { text-align: left; background-color: #f5f5f5; padding: 8px; border-bottom: 1px solid #ddd; }
          td { padding: 8px; border-bottom: 1px solid #eee; }
          .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 20px; }
          .summary { background-color: #e8eaf6; padding: 15px; border-radius: 8px; margin-bottom: 30px; text-align: center; }
          .summary h2 { margin: 0; color: #1a237e; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">Kobi's Atlas</div>
          <div class="subhead">Unofficial Academic Transcript</div>
        </div>

        <div class="user-info">
          <p><strong>Name:</strong> ${user?.displayName || 'Student'}</p>
          <p><strong>Email:</strong> ${user?.email || '-'}</p>
          <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
        </div>

        <div class="summary">
          <h2>Cumulative GPA: ${cgpa.toFixed(2)}</h2>
        </div>

        ${semesterRows}

        <div class="footer">
          <p>Generated by Kobi's Atlas App. This is not an official university document.</p>
        </div>
      </body>
    </html>
  `;
};

export const generateTranscript = async (user: User | null, semesters: Semester[]) => {
    try {
        const html = generateHTML(user, semesters);

        const { uri } = await printToFileAsync({
            html,
            base64: false
        });

        if (Platform.OS === 'web') {
            // On web, printToFileAsync isn't fully supported for download in the same way, 
            // often opens a print dialog. But expo-print on web usually opens a new tab.
            // If we want to force download/share, it's tricky on web.
            // Usually the print dialog is sufficient.
            return;
        }

        await shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('Error generating transcript:', error);
        throw error;
    }
};
